// dev-team's own guard cases, for the differential test (tests/differential.mjs).
// Generated once, when the bash guards were retired, from their suites
// (hooks/scripts/test-commit-guard.sh and test-local-review-guard.sh) and the
// hostile corpus they shared (hooks/scripts/testdata/hostile-commands.sh):
// every command a case ran, with the directory a review case ran in. This file
// is that record. A new case goes in tests/guard-cases.ts.
//
// @SANDBOX@ stands for the sandbox the differential builds from REVIEW_TREE:
// the tree under review at repo/, the scratch roots at tmp/ ($TMPDIR) and
// home/Developer/scratchpad, and links into and out of them.

// The shared hostile corpus: each line was a bypass of some guard once.
export const HOSTILE: readonly string[] = [
  "echo \"$(git push)\"",
  "x=\"$(git commit -m y)\"",
  "echo \\\"; git push; echo \\\"",
  "$'git' push origin x",
  "$\"git\" push",
  "git${IFS}push",
  "{git,} push",
  "=git push",
  "git -c alias.ci=commit ci -m x",
  "awk 'BEGIN{system(\"git push\")}'",
  "sed '1e git push' f",
  "echo \"$(gh pr merge 5)\"",
  "gh api -X PUT \"repos/o/r/pulls/5/merge?merge_method=squash\"",
  "# it's here\ngit push",
  "echo git push | sh",
  "printf \"git push\" | bash",
  "echo 'git commit -m x' | zsh",
  "echo git push | tclsh",
  "echo git push | xonsh",
  "echo hi # it's\ngit push\n# it's",
  "echo git push > x.sh; bash x.sh",
  "echo git push > x.sh; ./x.sh",
  "echo git push | xargs -I{} sh -c {}",
  "cat <(git push)",
  "echo git push > >(sh)",
  "rg --pre \"git push\" x",
  "git grep -O\"git push\" x",
  "git log; git push",
  "git log --grep x | git push",
  "grep x f || git push",
  "cd x && git push",
  "git push origin --fo\\\nrce",
  "git push $'--force'",
  "git push origin $'+main'",
  "\"git\" push -f",
  "\"bash\" -c 'true; rm README.md'",
  "\\bash -c 'true; rm README.md'",
  "$'sh' -c 'true; rm README.md'",
  "gawk '{ print > \"out.txt\" }' f",
  "mawk '{ print > \"out.txt\" }' f",
  "nawk '{ print > \"out.txt\" }' f",
  "awk '{ print | \"sh\" }' f",
  "awk 'BEGIN { system(\"rm README.md\") }'",
  "expect -c 'spawn sh; send \"rm README.md\"'",
  "echo 'x; rm README.md' | tclsh",
  "lua -e 'x; os.remove(\"README.md\")'",
  "pwsh -c 'x; Remove-Item README.md'",
  "Rscript -e 'x; file.remove(\"README.md\")'",
  "# it's a note\nrm README.md",
  "echo hi # it's\nrm README.md\n# it's",
  "echo rm README.md | xonsh",
  "echo \\'; rm README.md; echo \\'",
  "echo \\\"; rm README.md; echo \\\"",
  "echo \\'; git push; echo \\'",
  "echo x >&2'README.md'",
  "echo \"$(rm README.md)\"",
  "cat <<EOF\nit's\nEOF\nrm README.md",
  "sed 's/a/b/w out.txt' f",
  "grep -E 'x' f; git checkout -- f",
  "echo x | tee README.md",
  "git stash",
  "=rm README.md",
  "2>/dev/null rm README.md",
  ">README.md echo x",
  "FOO=1 rm README.md",
  "A=1 B=2 chmod 644 README.md",
  "doas rm README.md",
  "find . -exec rm {} \\;",
  "find . -name x -execdir rm README.md \\;",
  "{rm,README.md}",
  "rm {README,x}.md",
  "grep -rn 'x' . > README.md",
  "echo git push > x.sh; csh x.sh",
  "echo git push > x.sh; tcsh x.sh",
  "echo git push > x.sh; make -f x.sh",
  "git grep \"--open-files-in-pager=git push\" foo",
  "git grep \"-Ogit push\" foo",
  "rg \"--pre=git push\" foo",
  "git grep --open-files=git push foo",
  "git grep -nOgit push foo",
  "git -c alias.x='!rm README.md' x",
  "git -c core.pager='sh -c \"rm README.md\"' log",
  "git -c core.fsmonitor='rm README.md' status",
  "git -c diff.external='rm README.md' diff",
  "git -c gpg.program='rm README.md' log --show-signature",
  "git -c 'alias.x=!rm README.md; true' x",
  "git grep -O\"rm README.md\" x",
  "git grep -O git push x",
  "rg --pre git push foo",
  "git grep --open-files git push foo",
  "rg \"git push\" *",
  "git log --grep=push *",
  "grep -rn \"git push\" ?",
  "git log --format=%GG --grep=push",
  "git log --pretty=format:%G? --grep push",
  "git show --format=%GS push",
  "rg \"git push\" ^x",
  "git log --grep=push ^x",
  "grep -rn \"git push\" x#",
  "rg \"git push\" a~b",
  "echo git push > x.sh",
  "git log --grep push > out.txt",
  "echo git push >> ~/.bashrc",
]

// Every command the commit guard's bash suite ran, in any lane.
export const COMMIT_SUITE: readonly string[] = [
  " _X=1 git -C . push",
  "! git push",
  "\"git\" commit -m x",
  "\"git\" push -f",
  "# it's here\ngit push",
  "$\"git\" push",
  "$'git' push origin x",
  "'git' push",
  "'git' push origin :old",
  "(HUSKY=0 git push)",
  "(git push)",
  "/bin/bash -c \"cd x && git push\"",
  "/opt/homebrew/bin/gh pr merge 5",
  "/opt/homebrew/bin/git -C . commit -m x",
  "/usr/bin/env git push",
  "/usr/bin/git push",
  "2>&1 git commit -m x",
  "2>/dev/null git push",
  "2>/dev/null git push --force",
  "2>/dev/null grep -rn git push .",
  "=git push",
  ">log git push",
  "A=\"x\ny\" git push",
  "A=\"x | y\" B=1 git push",
  "A=1 B=\"x y\" git push",
  "A=1 B=2 git push +main",
  "A=1 B=2 git push origin x",
  "A=it\\'s git push",
  "A=x\\\"y git push",
  "FOO=1 make && git push",
  "GH_TOKEN=x gh pr merge 5",
  "GIT_TRACE=1 git push",
  "HUSKY=0 git commit -m x",
  "HUSKY=0 npm test \"unit\" && git commit -m \"fix, then git push\"",
  "M='a && b' git push",
  "MSG=\"a; b\" git commit -m x",
  "SKIP=lint git commit -m x",
  "\\gh pr merge 5",
  "\\git commit -m x",
  "\\git push -f",
  "awk 'BEGIN { system(\"git push --force\") }'",
  "awk 'BEGIN{system(\"git push\")}'",
  "bash -c \"echo commit\"",
  "bash -c \"gh pr merge 5\"",
  "bash -c \"git push\"",
  "bash -x -c \"git push\"",
  "bash run-tests.sh && git push",
  "caffeinate git push",
  "cat .git/COMMIT_EDITMSG",
  "cat <(git push)",
  "cat notes | grep git push",
  "cd x\nGIT_TRACE=1 git push",
  "cd x\nenv git push",
  "cd x && HUSKY=0 git commit -m y",
  "cd x && gh pr merge 5 --admin",
  "cd x && git commit -am y",
  "cd x && git log --grep push | head",
  "digit push --force",
  "doas gh pr merge 5",
  "doas git push",
  "doas git push --force",
  "echo \"$(gh pr merge 5)\"",
  "echo \"$(git push)\"",
  "echo \"run git push later\"",
  "echo $(git commit -m x)",
  "echo \\\"; git push; echo \\\"",
  "echo `git push`",
  "echo git push",
  "echo git push > x.sh; ./x.sh",
  "echo git push | sh",
  "env GIT_DIR=x git commit -m y",
  "env gh pr merge 5",
  "env git commit -m x",
  "env git push",
  "eval \"git push\"",
  "eval 'gh -R o/r pr merge 5'",
  "export HUSKY=0; git push",
  "find . -exec git commit -m x \\;",
  "find . -exec git push -f \\;",
  "find . -execdir git push \\;",
  "flock /tmp/l git push",
  "gh --repo o/r pr  merge",
  "gh -R o/r pr merge 5",
  "gh api -X PUT \"repos/o/r/pulls/5/merge?merge_method=squash\"",
  "gh api -X PUT repos/o/r/pulls/5/merge",
  "gh api repos/o/r/pulls/5/merge -X PUT",
  "gh api repos/o/r/pulls/5/mergeable",
  "gh pr checks 5",
  "gh pr list",
  "gh pr merge 5",
  "gh pr merge 5 --squash --delete-branch",
  "gh pr view 5 --json mergeable",
  "gh search prs \"pr merge\"",
  "ghx pr merge 5",
  "git \"commit\" -m x",
  "git \"push\" --force",
  "git --git-dir x --work-tree y push",
  "git --git-dir=x commit -m y",
  "git --no-pager push",
  "git -C \"a b\" -c user.name=\"M B\" commit -m x",
  "git -C . push origin feat",
  "git -C /repo push origin main",
  "git -C /x push --force",
  "git -C dir commit -m x",
  "git -c alias.ci=commit ci -m x",
  "git -c core.hooksPath=/dev/null commit -m x",
  "git -c k=v push",
  "git -c user.name=x commit -F msg.txt",
  "git \\\ncommit -m x",
  "git \\\npush -f",
  "git commit -F - <<'EOF'\nfix: x\n\nDEBUG=1 makes 'it' verbose; don't git push\nEOF",
  "git commit -m \"a=b c\"",
  "git commit -m \"fix: x\"",
  "git commit -m \"load env\"",
  "git commit -m \"set X=1 in config\"",
  "git commit -m \"x; A=1\" && git push",
  "git commit -m 'y | B=\"2\"' && git push",
  "git commit -m x",
  "git commit -m x && git push",
  "git commit -m x && git push -f",
  "git commit-tree HEAD^{tree} -m x",
  "git diff",
  "git diff -- hooks/scripts/commit-guard.sh",
  "git diff HEAD",
  "git grep push",
  "git log --format=%s | grep -c push",
  "git log --grep \"fix git push\" --oneline",
  "git log --grep commit",
  "git log --grep=commit",
  "git log --grep=push -- *",
  "git log --grep=x && git push",
  "git log --oneline",
  "git log --oneline && git grep -n commit",
  "git log --oneline -5",
  "git log -S \"git commit\" --oneline",
  "git log | grep commit",
  "git log | grep push",
  "git log; doas git push",
  "git merge origin/main",
  "git push",
  "git push $'--force'",
  "git push --delete origin x",
  "git push --dry-run",
  "git push --follow-tags",
  "git push --forc",
  "git push --force",
  "git push --force-if-includes",
  "git push --force-with-lease",
  "git push --mirror",
  "git push --no-verify",
  "git push --prune origin",
  "git push -d origin x",
  "git push -f",
  "git push -oF",
  "git push -u origin feat/add-d",
  "git push -u origin feat/x",
  "git push -uf origin x",
  "git push origin $'+main'",
  "git push origin +main",
  "git push origin --fo\\\nrce",
  "git push origin :old",
  "git push origin HEAD:refs/heads/x",
  "git show HEAD -- commit-guard.sh",
  "git status",
  "git status\ngit push",
  "git status | git push",
  "git status | grep \"git push\"",
  "git status || git push",
  "git status; echo commit",
  "git status; echo push",
  "git status; git commit -m x",
  "git${IFS}push",
  "grep -E 'git (commit|push)' x.md",
  "grep -n 'git commit' skills/x.md",
  "grep -rn \"git commit\" .",
  "grep -rn \"git push\" README.md",
  "grep -rn \"git push\" README.md; git push",
  "grep -rn git push .",
  "grep -rn push README.md",
  "if git push; then echo y; fi",
  "ionice -c3 git push",
  "ls .git/refs/push",
  "ls /usr/bin/git",
  "nocorrect git push",
  "noglob git push",
  "parallel git push ::: a",
  "printenv && git push",
  "printf \"%s\" git commit",
  "rg \"gh pr merge\"",
  "rg --pre \"git push\" x",
  "rg -n \"gh api repos/o/r/pulls/5/merge\" .",
  "sed '1e git push' f",
  "sh -c 'git commit -m x'",
  "stdbuf -oL git push",
  "stdbuf -oL git push --delete origin x",
  "sudo git push",
  "time git push",
  "watch git push",
  "x=\"$(git commit -m y)\"",
  "xargs git commit -m x",
  "zsh -lc 'git push'",
  "{ git push; }",
  "{git,} push",
]

// Every command the review guard's bash suite ran as a reviewer, with its
// working directory (empty when none was given).
export const REVIEW_SUITE: readonly (readonly [string, string])[] = [
  ["chmod 644 @SANDBOX@/repo/agents/lint-holmes-local-mode.sh", ""],
  ["touch @SANDBOX@/tmp/probe", ""],
  ["touch @SANDBOX@/home/Developer/scratchpad/probe", ""],
  ["rm -rf @SANDBOX@/tmp", ""],
  ["touch @SANDBOX@/home/notes.txt", ""],
  ["touch @SANDBOX@/linked-home/Developer/scratchpad/x", ""],
  ["git -C @SANDBOX@/repo status --short", ""],
  ["git -C @SANDBOX@/repo diff HEAD", ""],
  ["git -C @SANDBOX@/repo ls-files --others --exclude-standard", ""],
  ["git -C @SANDBOX@/repo status -sb", ""],
  ["git rev-parse --short HEAD", ""],
  ["git log --oneline -5", ""],
  ["git show HEAD:file.txt", ""],
  ["git blame file.txt", ""],
  ["bash run-tests.sh", ""],
  ["npm test", ""],
  ["grep -i needle file.txt", ""],
  ["rg --files", ""],
  ["cat @SANDBOX@/repo/file.txt", ""],
  ["git restore .", ""],
  ["git restore --staged --worktree src/", ""],
  ["git -C @SANDBOX@/repo restore agents/lint.sh", ""],
  ["git checkout -- .", ""],
  ["git switch main", ""],
  ["git stash", ""],
  ["git stash push -m wip", ""],
  ["git reset --hard HEAD", ""],
  ["git clean -fd", ""],
  ["git commit -m x", ""],
  ["git apply patch.diff", ""],
  ["chmod 644 agents/lint-holmes-local-mode.sh", ""],
  ["chmod +x run-tests.sh", ""],
  ["chown mike file.txt", ""],
  ["rm -rf build", ""],
  ["mv old.txt new.txt", ""],
  ["truncate -s 0 file.txt", ""],
  ["sed -i '' s/a/b/ file.txt", ""],
  ["perl -i -pe s/a/b/ file.txt", ""],
  ["npx prettier --write .", ""],
  ["ruff check --fix .", ""],
  ["find . -name '*.tmp' -delete", ""],
  ["xargs -0 rm", ""],
  ["sudo rm -rf /", ""],
  ["git status && chmod 644 file.txt", ""],
  ["rm -rf @SANDBOX@/tmp/scratch/build", "@SANDBOX@/tmp/scratch"],
  ["rm -f notes.txt", "@SANDBOX@/tmp/scratch"],
  ["mv a.txt b.txt", "@SANDBOX@/tmp/scratch"],
  ["cp @SANDBOX@/repo/src/file.txt @SANDBOX@/tmp/scratch/copy.txt", "@SANDBOX@/tmp/scratch"],
  ["cp -r @SANDBOX@/repo/src @SANDBOX@/tmp/scratch/", "@SANDBOX@/tmp/scratch"],
  ["tee @SANDBOX@/tmp/scratch/log.txt", "@SANDBOX@/tmp/scratch"],
  ["touch @SANDBOX@/tmp/scratch/stamp", "@SANDBOX@/tmp/scratch"],
  ["ln -s @SANDBOX@/repo/src @SANDBOX@/tmp/scratch/src-link", "@SANDBOX@/tmp/scratch"],
  ["install -m 644 @SANDBOX@/repo/file.txt @SANDBOX@/tmp/scratch/file.txt", "@SANDBOX@/tmp/scratch"],
  ["dd if=@SANDBOX@/repo/file.txt of=@SANDBOX@/tmp/scratch/file.bin", "@SANDBOX@/tmp/scratch"],
  ["patch -d @SANDBOX@/tmp/scratch -p1 -i @SANDBOX@/tmp/scratch/fix.diff", "@SANDBOX@/tmp/scratch"],
  ["chmod 644 @SANDBOX@/tmp/scratch/file.txt", "@SANDBOX@/tmp/scratch"],
  ["cp @SANDBOX@/tmp/scratch/file.txt @SANDBOX@/repo/src/file.txt", "@SANDBOX@/tmp/scratch"],
  ["cp -t @SANDBOX@/repo/src @SANDBOX@/tmp/scratch/file.txt", "@SANDBOX@/tmp/scratch"],
  ["cp --target-directory=@SANDBOX@/repo @SANDBOX@/tmp/scratch/file.txt", "@SANDBOX@/tmp/scratch"],
  ["tee -a @SANDBOX@/repo/notes.md", "@SANDBOX@/tmp/scratch"],
  ["touch @SANDBOX@/repo/new.txt", "@SANDBOX@/tmp/scratch"],
  ["ln -s @SANDBOX@/tmp/scratch/x @SANDBOX@/repo/x", "@SANDBOX@/tmp/scratch"],
  ["install -d @SANDBOX@/repo/newdir", "@SANDBOX@/tmp/scratch"],
  ["install @SANDBOX@/tmp/scratch/file.txt @SANDBOX@/repo/file.txt", "@SANDBOX@/tmp/scratch"],
  ["dd if=/dev/zero of=@SANDBOX@/repo/file.txt", "@SANDBOX@/tmp/scratch"],
  ["patch -d @SANDBOX@/repo -p1 -i @SANDBOX@/tmp/scratch/fix.diff", "@SANDBOX@/tmp/scratch"],
  ["patch --directory=@SANDBOX@/repo -p1", "@SANDBOX@/tmp/scratch"],
  ["rm -rf @SANDBOX@/repo/src", "@SANDBOX@/tmp/scratch"],
  ["mv @SANDBOX@/repo/src/file.txt @SANDBOX@/tmp/scratch/", "@SANDBOX@/tmp/scratch"],
  ["rm -rf @SANDBOX@", "@SANDBOX@/tmp/scratch"],
  ["rm -rf @SANDBOX@/tmp/link-into-tree/file.txt", "@SANDBOX@/tmp/scratch"],
  ["touch @SANDBOX@/tmp/link-into-tree/new.txt", "@SANDBOX@/tmp/scratch"],
  ["rm -rf ~/definitely-not-the-tree", "@SANDBOX@/tmp/scratch"],
  ["rm -rf $DIR", "@SANDBOX@/tmp/scratch"],
  ["rm -f @SANDBOX@/tmp/scratch/*.tmp", "@SANDBOX@/tmp/scratch"],
  ["touch \"@SANDBOX@/tmp/scratch/a b\"", "@SANDBOX@/tmp/scratch"],
  ["cp x $(mktemp)", "@SANDBOX@/tmp/scratch"],
  ["find . -name x | xargs rm", "@SANDBOX@/tmp/scratch"],
  ["touch notes.txt", ""],
  ["rm @SANDBOX@/repo/link-out", "@SANDBOX@/tmp/scratch"],
  ["rm -f @SANDBOX@/repo/dir-link-out", "@SANDBOX@/tmp/scratch"],
  ["unlink @SANDBOX@/repo/link-out", "@SANDBOX@/tmp/scratch"],
  ["mv @SANDBOX@/repo/link-out @SANDBOX@/tmp/scratch/moved", "@SANDBOX@/tmp/scratch"],
  ["chmod -h 644 @SANDBOX@/repo/link-out", "@SANDBOX@/tmp/scratch"],
  ["rm link-out", "@SANDBOX@/repo"],
  ["rm @SANDBOX@/tmp/scratch/target.txt", "@SANDBOX@/tmp/scratch"],
  ["patch -p1 -i @SANDBOX@/tmp/scratch/fix.diff", "@SANDBOX@/repo"],
  ["mkdir newdir", "@SANDBOX@/repo"],
  ["mkdir -p -m 755 @SANDBOX@/repo/a/b", "@SANDBOX@/repo"],
  ["rsync -a @SANDBOX@/tmp/scratch/ @SANDBOX@/repo/", "@SANDBOX@/repo"],
  ["rsync -a @SANDBOX@/tmp/scratch/ newdir/", "@SANDBOX@/repo"],
  ["rsync -a --remove-source-files README.md @SANDBOX@/tmp/scratch/", "@SANDBOX@/repo"],
  ["tar -xf @SANDBOX@/tmp/scratch/a.tar -C @SANDBOX@/repo", "@SANDBOX@/repo"],
  ["tar -xf @SANDBOX@/tmp/scratch/a.tar", "@SANDBOX@/repo"],
  ["tar xzf @SANDBOX@/tmp/scratch/a.tgz", "@SANDBOX@/repo"],
  ["tar --extract --file=@SANDBOX@/tmp/scratch/a.tar --directory=@SANDBOX@/repo", "@SANDBOX@/repo"],
  ["tar -czf @SANDBOX@/repo/out.tgz @SANDBOX@/tmp/scratch", "@SANDBOX@/repo"],
  ["unzip @SANDBOX@/tmp/scratch/a.zip -d @SANDBOX@/repo", "@SANDBOX@/repo"],
  ["unzip @SANDBOX@/tmp/scratch/a.zip", "@SANDBOX@/repo"],
  ["unzip -o @SANDBOX@/tmp/scratch/a.zip", "@SANDBOX@/repo"],
  ["sort -o README.md README.md", "@SANDBOX@/repo"],
  ["sort -uo README.md README.md", "@SANDBOX@/repo"],
  ["sort --output=README.md README.md", "@SANDBOX@/repo"],
  ["uniq @SANDBOX@/tmp/scratch/in.txt README.md", "@SANDBOX@/repo"],
  ["gofmt -w main.go", "@SANDBOX@/repo"],
  ["gofmt -l -w .", "@SANDBOX@/repo"],
  ["goimports -w main.go", "@SANDBOX@/repo"],
  ["prettier -w src", "@SANDBOX@/repo"],
  ["npx prettier -w src", "@SANDBOX@/repo"],
  ["shfmt -w run-tests.sh", "@SANDBOX@/repo"],
  ["shfmt -l -w .", "@SANDBOX@/repo"],
  ["clang-format -i main.c", "@SANDBOX@/repo"],
  ["black app.py", "@SANDBOX@/repo"],
  ["black .", "@SANDBOX@/repo"],
  ["python3 -m black app.py", "@SANDBOX@/repo"],
  ["rustfmt src/main.rs", "@SANDBOX@/repo"],
  ["cargo fmt", "@SANDBOX@/repo"],
  ["cargo +nightly fmt --all", "@SANDBOX@/repo"],
  ["go fmt ./...", "@SANDBOX@/repo"],
  ["ruff format app.py", "@SANDBOX@/repo"],
  ["isort app.py", "@SANDBOX@/repo"],
  ["terraform fmt", "@SANDBOX@/repo"],
  ["mix format", "@SANDBOX@/repo"],
  ["env -u FOO chmod 644 README.md", "@SANDBOX@/repo"],
  ["env -u FOO -P /usr/bin chmod 644 README.md", "@SANDBOX@/repo"],
  ["env -S 'chmod 644 README.md'", "@SANDBOX@/repo"],
  ["sudo -u root chmod 644 README.md", "@SANDBOX@/repo"],
  ["xargs -n 1 rm", "@SANDBOX@/repo"],
  ["doas chmod 644 @SANDBOX@/repo/README.md", "@SANDBOX@/repo"],
  ["doas -u root chmod 644 README.md", "@SANDBOX@/repo"],
  ["doas -n -C /etc/doas.conf chmod 644 README.md", "@SANDBOX@/repo"],
  ["doas -a passwd rm README.md", "@SANDBOX@/repo"],
  ["nice chmod 644 @SANDBOX@/repo/README.md", "@SANDBOX@/repo"],
  ["nice -n 10 chmod 644 README.md", "@SANDBOX@/repo"],
  ["nice -n -5 rm README.md", "@SANDBOX@/repo"],
  ["nice --adjustment 10 chmod 644 README.md", "@SANDBOX@/repo"],
  ["nice --adjustment=10 chmod 644 README.md", "@SANDBOX@/repo"],
  ["nice -n10 chmod 644 README.md", "@SANDBOX@/repo"],
  ["nice -10 chmod 644 README.md", "@SANDBOX@/repo"],
  ["ionice chmod 644 @SANDBOX@/repo/README.md", "@SANDBOX@/repo"],
  ["ionice -c 3 chmod 644 README.md", "@SANDBOX@/repo"],
  ["ionice -c 2 -n 7 rm README.md", "@SANDBOX@/repo"],
  ["ionice --class 3 --classdata 7 chmod 644 README.md", "@SANDBOX@/repo"],
  ["ionice -c3 -t chmod 644 README.md", "@SANDBOX@/repo"],
  ["stdbuf chmod 644 @SANDBOX@/repo/README.md", "@SANDBOX@/repo"],
  ["stdbuf -oL chmod 644 README.md", "@SANDBOX@/repo"],
  ["stdbuf -o L -e 0 chmod 644 README.md", "@SANDBOX@/repo"],
  ["stdbuf -i 0 --output L rm README.md", "@SANDBOX@/repo"],
  ["stdbuf --output=L chmod 644 README.md", "@SANDBOX@/repo"],
  ["timeout 5 chmod 644 @SANDBOX@/repo/README.md", "@SANDBOX@/repo"],
  ["timeout 1.5m rm README.md", "@SANDBOX@/repo"],
  ["timeout -s KILL 5 chmod 644 README.md", "@SANDBOX@/repo"],
  ["timeout --signal=TERM -k 2 5 chmod 644 README.md", "@SANDBOX@/repo"],
  ["timeout --signal TERM --kill-after 2s 5 rm README.md", "@SANDBOX@/repo"],
  ["timeout -sKILL -k2 --foreground --preserve-status -v 5 chmod 644 README.md", "@SANDBOX@/repo"],
  ["noglob chmod 644 @SANDBOX@/repo/README.md", "@SANDBOX@/repo"],
  ["noglob rm README.md", "@SANDBOX@/repo"],
  ["nice -n 10 ionice -c 3 stdbuf -oL doas -u root chmod 644 README.md", "@SANDBOX@/repo"],
  ["noglob timeout -s KILL 5 nice chmod 644 README.md", "@SANDBOX@/repo"],
  ["/usr/bin/command chmod 644 README.md", "@SANDBOX@/repo"],
  ["/usr/bin/builtin chmod 644 README.md", "@SANDBOX@/repo"],
  ["/bin/exec chmod 644 README.md", "@SANDBOX@/repo"],
  ["/usr/bin/sudo chmod 644 README.md", "@SANDBOX@/repo"],
  ["/usr/bin/doas chmod 644 README.md", "@SANDBOX@/repo"],
  ["/usr/bin/nohup chmod 644 README.md", "@SANDBOX@/repo"],
  ["/usr/bin/nice chmod 644 @SANDBOX@/repo/README.md", "@SANDBOX@/repo"],
  ["/usr/bin/ionice -c 3 chmod 644 README.md", "@SANDBOX@/repo"],
  ["/usr/bin/stdbuf -oL chmod 644 README.md", "@SANDBOX@/repo"],
  ["/usr/bin/timeout 5 chmod 644 README.md", "@SANDBOX@/repo"],
  ["/bin/noglob chmod 644 README.md", "@SANDBOX@/repo"],
  ["/usr/bin/time chmod 644 README.md", "@SANDBOX@/repo"],
  ["/usr/bin/env -u FOO chmod 644 README.md", "@SANDBOX@/repo"],
  ["/usr/bin/xargs -0 rm", "@SANDBOX@/repo"],
  ["/usr/local/bin/npx chmod 644 README.md", "@SANDBOX@/repo"],
  ["/opt/bun/bin/bunx chmod 644 README.md", "@SANDBOX@/repo"],
  ["/usr/local/bin/pnpx chmod 644 README.md", "@SANDBOX@/repo"],
  ["sudo -nu root chmod 644 README.md", "@SANDBOX@/repo"],
  ["sudo -bD /x rm README.md", "@SANDBOX@/repo"],
  ["doas -nu root chmod 644 README.md", "@SANDBOX@/repo"],
  ["ionice -tc 3 chmod 644 README.md", "@SANDBOX@/repo"],
  ["timeout -vs KILL 5 chmod 644 README.md", "@SANDBOX@/repo"],
  ["timeout -fk 2 5 rm README.md", "@SANDBOX@/repo"],
  ["env -iu FOO chmod 644 README.md", "@SANDBOX@/repo"],
  ["env -iC /x rm README.md", "@SANDBOX@/repo"],
  ["env -iS'chmod 644 README.md'", "@SANDBOX@/repo"],
  ["xargs -0n 1 rm", "@SANDBOX@/repo"],
  ["time -po /dev/null chmod 644 README.md", "@SANDBOX@/repo"],
  ["npx -yp pkg chmod 644 README.md", "@SANDBOX@/repo"],
  ["nice --adj 10 chmod 644 README.md", "@SANDBOX@/repo"],
  ["stdbuf --out L chmod 644 README.md", "@SANDBOX@/repo"],
  ["ionice --cl 3 rm README.md", "@SANDBOX@/repo"],
  ["timeout --sig KILL 5 rm README.md", "@SANDBOX@/repo"],
  ["timeout --kill 2 5 chmod 644 README.md", "@SANDBOX@/repo"],
  ["sudo --us root chmod 644 README.md", "@SANDBOX@/repo"],
  ["sudo --chd /x rm README.md", "@SANDBOX@/repo"],
  ["env --un FOO chmod 644 README.md", "@SANDBOX@/repo"],
  ["env --ch /x rm README.md", "@SANDBOX@/repo"],
  ["env --spl='chmod 644 README.md'", "@SANDBOX@/repo"],
  ["time --out /dev/null chmod 644 README.md", "@SANDBOX@/repo"],
  ["npx --pack pkg chmod 644 README.md", "@SANDBOX@/repo"],
  ["xargs --max-args 1 rm", "@SANDBOX@/repo"],
  ["xargs --max-a 1 rm", "@SANDBOX@/repo"],
  ["xargs --max-procs 2 rm", "@SANDBOX@/repo"],
  ["xargs --max-p 2 rm", "@SANDBOX@/repo"],
  ["xargs --max-chars 100 rm", "@SANDBOX@/repo"],
  ["xargs --max-c 100 rm", "@SANDBOX@/repo"],
  ["xargs --arg-file /x rm", "@SANDBOX@/repo"],
  ["xargs --arg /x rm", "@SANDBOX@/repo"],
  ["xargs --delimiter , rm", "@SANDBOX@/repo"],
  ["xargs --delim , rm", "@SANDBOX@/repo"],
  ["xargs --process-slot-var V rm", "@SANDBOX@/repo"],
  ["xargs --proc V rm", "@SANDBOX@/repo"],
  ["/usr/local/bin/bundle exec chmod 644 @SANDBOX@/repo/README.md", "@SANDBOX@/repo"],
  ["/usr/local/bin/uv run chmod 644 README.md", "@SANDBOX@/repo"],
  ["/usr/local/bin/poetry run chmod 644 README.md", "@SANDBOX@/repo"],
  ["/usr/local/bin/pipx run chmod 644 README.md", "@SANDBOX@/repo"],
  ["/usr/local/bin/pnpm exec chmod 644 README.md", "@SANDBOX@/repo"],
  ["/usr/local/bin/npm exec chmod 644 README.md", "@SANDBOX@/repo"],
  ["/usr/local/bin/yarn chmod 644 README.md", "@SANDBOX@/repo"],
  ["/usr/local/bin/composer exec chmod 644 README.md", "@SANDBOX@/repo"],
  ["nice -n 10 git status", "@SANDBOX@/repo"],
  ["ionice -c 3 git log --oneline", "@SANDBOX@/repo"],
  ["stdbuf -oL git diff", "@SANDBOX@/repo"],
  ["doas -u root git status", "@SANDBOX@/repo"],
  ["timeout -s KILL 5 git status", "@SANDBOX@/repo"],
  ["noglob git log --oneline", "@SANDBOX@/repo"],
  ["/usr/bin/nice -n 10 git status", "@SANDBOX@/repo"],
  ["sudo -nu root git status", "@SANDBOX@/repo"],
  ["timeout --sig KILL 5 git diff", "@SANDBOX@/repo"],
  ["env -- git status", "@SANDBOX@/repo"],
  ["/usr/local/bin/npm test", "@SANDBOX@/repo"],
  ["/usr/local/bin/yarn test", "@SANDBOX@/repo"],
  ["/usr/local/bin/yarn install", "@SANDBOX@/repo"],
  ["/usr/local/bin/uv run pytest", "@SANDBOX@/repo"],
  ["/usr/local/bin/bundle exec rspec", "@SANDBOX@/repo"],
  ["prettier --check .", "@SANDBOX@/repo"],
  ["prettier -c .", "@SANDBOX@/repo"],
  ["black --check .", "@SANDBOX@/repo"],
  ["black --diff app.py", "@SANDBOX@/repo"],
  ["gofmt -l .", "@SANDBOX@/repo"],
  ["gofmt -d main.go", "@SANDBOX@/repo"],
  ["shfmt -d run-tests.sh", "@SANDBOX@/repo"],
  ["cargo fmt --check", "@SANDBOX@/repo"],
  ["cargo fmt -- --check", "@SANDBOX@/repo"],
  ["rustfmt --check src/main.rs", "@SANDBOX@/repo"],
  ["go fmt -n ./...", "@SANDBOX@/repo"],
  ["ruff format --check .", "@SANDBOX@/repo"],
  ["ruff check .", "@SANDBOX@/repo"],
  ["isort --check-only app.py", "@SANDBOX@/repo"],
  ["terraform fmt -check", "@SANDBOX@/repo"],
  ["mix format --check-formatted", "@SANDBOX@/repo"],
  ["clang-format main.c", "@SANDBOX@/repo"],
  ["black --version", "@SANDBOX@/repo"],
  ["mkdir -p @SANDBOX@/tmp/scratch/probe", "@SANDBOX@/repo"],
  ["rsync -a @SANDBOX@/repo/ @SANDBOX@/tmp/scratch/copy/", "@SANDBOX@/repo"],
  ["rsync -a README.md @SANDBOX@/tmp/scratch/", "@SANDBOX@/repo"],
  ["tar -tf @SANDBOX@/tmp/scratch/a.tar", "@SANDBOX@/repo"],
  ["tar -cf @SANDBOX@/tmp/scratch/tree.tar .", "@SANDBOX@/repo"],
  ["tar -xf @SANDBOX@/tmp/scratch/a.tar -C @SANDBOX@/tmp/scratch", "@SANDBOX@/repo"],
  ["tar -xOf @SANDBOX@/tmp/scratch/a.tar README.md", "@SANDBOX@/repo"],
  ["unzip -l @SANDBOX@/tmp/scratch/a.zip", "@SANDBOX@/repo"],
  ["unzip @SANDBOX@/tmp/scratch/a.zip -d @SANDBOX@/tmp/scratch/x", "@SANDBOX@/repo"],
  ["sort README.md", "@SANDBOX@/repo"],
  ["sort -o @SANDBOX@/tmp/scratch/sorted.txt README.md", "@SANDBOX@/repo"],
  ["uniq README.md", "@SANDBOX@/repo"],
  ["uniq README.md @SANDBOX@/tmp/scratch/u.txt", "@SANDBOX@/repo"],
  ["env -u FOO ls", "@SANDBOX@/repo"],
  ["env FOO=1 bash run-tests.sh", "@SANDBOX@/repo"],
  ["ln -s @SANDBOX@/tmp/scratch/x", "@SANDBOX@/repo"],
  ["rubocop --autocorrect", "@SANDBOX@/repo"],
  ["rubocop --autocorrect-all", "@SANDBOX@/repo"],
  ["rubocop --auto-correct", "@SANDBOX@/repo"],
  ["rubocop --auto-correct-all", "@SANDBOX@/repo"],
  ["rubocop -x", "@SANDBOX@/repo"],
  ["rubocop --fix-layout", "@SANDBOX@/repo"],
  ["bundle exec rubocop -a", "@SANDBOX@/repo"],
  ["uv run black .", "@SANDBOX@/repo"],
  ["uv run --with black black .", "@SANDBOX@/repo"],
  ["poetry run black .", "@SANDBOX@/repo"],
  ["poetry -C sub run black .", "@SANDBOX@/repo"],
  ["pipx run black .", "@SANDBOX@/repo"],
  ["pnpm exec prettier -w .", "@SANDBOX@/repo"],
  ["pnpm dlx prettier -w .", "@SANDBOX@/repo"],
  ["npm exec -- prettier -w .", "@SANDBOX@/repo"],
  ["npm x prettier -w .", "@SANDBOX@/repo"],
  ["npm exec -c 'prettier -w .'", "@SANDBOX@/repo"],
  ["yarn prettier -w .", "@SANDBOX@/repo"],
  ["yarn exec prettier -w .", "@SANDBOX@/repo"],
  ["yarn dlx prettier -w .", "@SANDBOX@/repo"],
  ["yarn run prettier -w .", "@SANDBOX@/repo"],
  ["composer exec pint", "@SANDBOX@/repo"],
  ["vendor/bin/pint", "@SANDBOX@/repo"],
  ["pint app", "@SANDBOX@/repo"],
  ["php-cs-fixer fix src", "@SANDBOX@/repo"],
  ["vendor/bin/php-cs-fixer fix", "@SANDBOX@/repo"],
  ["rustfmt --print-config default rustfmt.toml", "@SANDBOX@/repo"],
  ["rustfmt --print-config=minimal m.toml", "@SANDBOX@/repo"],
  ["command black app.py", "@SANDBOX@/repo"],
  ["terraform fmt -check=false", "@SANDBOX@/repo"],
  ["command -v black", "@SANDBOX@/repo"],
  ["command -v rustfmt", "@SANDBOX@/repo"],
  ["command -v unzip", "@SANDBOX@/repo"],
  ["command -V isort", "@SANDBOX@/repo"],
  ["command -pv black", "@SANDBOX@/repo"],
  ["unzip -h", "@SANDBOX@/repo"],
  ["unzip", "@SANDBOX@/repo"],
  ["rustfmt --print-config default", "@SANDBOX@/repo"],
  ["rustfmt --print-config current src/main.rs", "@SANDBOX@/repo"],
  ["rustfmt --help=config", "@SANDBOX@/repo"],
  ["isort --show-config", "@SANDBOX@/repo"],
  ["black -c 'x=1'", "@SANDBOX@/repo"],
  ["black --code=x", "@SANDBOX@/repo"],
  ["uniq --skip-fields 1 README.md", "@SANDBOX@/repo"],
  ["uniq --skip-chars 2 README.md", "@SANDBOX@/repo"],
  ["uniq --check-chars 3 README.md", "@SANDBOX@/repo"],
  ["which black", "@SANDBOX@/repo"],
  ["type black", "@SANDBOX@/repo"],
  ["command -v rm", "@SANDBOX@/repo"],
  ["npm test", "@SANDBOX@/repo"],
  ["yarn test", "@SANDBOX@/repo"],
  ["yarn install", "@SANDBOX@/repo"],
  ["uv run pytest", "@SANDBOX@/repo"],
  ["bundle exec rspec", "@SANDBOX@/repo"],
  ["poetry run pytest", "@SANDBOX@/repo"],
  ["pipx run pytest", "@SANDBOX@/repo"],
  ["pnpm exec vitest", "@SANDBOX@/repo"],
  ["vendor/bin/pint --test", "@SANDBOX@/repo"],
  ["pint --test", "@SANDBOX@/repo"],
  ["php-cs-fixer fix --dry-run", "@SANDBOX@/repo"],
  ["php-cs-fixer check", "@SANDBOX@/repo"],
  ["rubocop", "@SANDBOX@/repo"],
  ["yapf -ir .", "@SANDBOX@/repo"],
  ["yapf -ri .", "@SANDBOX@/repo"],
  ["python3 -m yapf -ir .", "@SANDBOX@/repo"],
  ["autopep8 -ai x.py", "@SANDBOX@/repo"],
  ["autopep8 -ia x.py", "@SANDBOX@/repo"],
  ["prettier -lw .", "@SANDBOX@/repo"],
  ["rubocop -aD", "@SANDBOX@/repo"],
  ["bundle exec rubocop -Da", "@SANDBOX@/repo"],
  ["black - app.py", "@SANDBOX@/repo"],
  ["black -", "@SANDBOX@/repo"],
  ["cat x.py | black -q -", "@SANDBOX@/repo"],
  ["black --stdin-filename x.py -", "@SANDBOX@/repo"],
  ["isort -", "@SANDBOX@/repo"],
  ["echo code | rustfmt", "@SANDBOX@/repo"],
  ["clang-format -sort-includes main.c", "@SANDBOX@/repo"],
  ["yapf -dr .", "@SANDBOX@/repo"],
  ["yapf -l1-9i -d x.py", "@SANDBOX@/repo"],
  ["autopep8 -d x.py", "@SANDBOX@/repo"],
  ["prettier -lc .", "@SANDBOX@/repo"],
  ["rubocop -D", "@SANDBOX@/repo"],
  ["git branch --show-current", ""],
  ["git branch", ""],
  ["git branch -a -v", ""],
  ["git branch --list feature/*", ""],
  ["git remote -v", ""],
  ["git remote get-url origin", ""],
  ["git config --get remote.origin.url", ""],
  ["git config --list", ""],
  ["git config get user.name", ""],
  ["git stash list", ""],
  ["git stash show -p", ""],
  ["git worktree list", ""],
  ["git tag -l v1.*", ""],
  ["git tag", ""],
  ["git tag -n5", ""],
  ["git ls-remote origin", ""],
  ["git branch --contains abc1234", ""],
  ["git branch -r --no-contains abc1234", ""],
  ["git branch --merged main", ""],
  ["git tag --contains abc1234", ""],
  ["git tag --points-at HEAD", ""],
  ["git branch -D feature", ""],
  ["git branch new-branch", ""],
  ["git branch -m old new", ""],
  ["git remote add upstream x", ""],
  ["git remote remove origin", ""],
  ["git config user.name x", ""],
  ["git config --add a.b c", ""],
  ["git config --get a.b --unset", ""],
  ["git stash drop", ""],
  ["git stash pop", ""],
  ["git worktree add ../x", ""],
  ["git tag v2", ""],
  ["git tag -d v1", ""],
  ["git tag -l -d v1", ""],
  ["git branch --contains abc1234 new-branch", ""],
  ["perl -pi -e s/a/b/ file.txt", ""],
  ["perl -ni -e print file.txt", ""],
  ["perl -pi.bak -e s/a/b/ file.txt", ""],
  ["perl -lpi -e s/a/b/ file.txt", ""],
  ["sed -ie s/a/b/ file.txt", ""],
  ["ruby -pi -e x file.txt", ""],
  ["ruby -i.bak -pe x file.txt", ""],
  ["sed --in-place s/a/b/ file.txt", ""],
  ["sed -I s/a/b/ file.txt", ""],
  ["sed -I.bak s/a/b/ file.txt", ""],
  ["sed -nI s/a/b/ file.txt", ""],
  ["sed -li s/a/b/ file.txt", ""],
  ["sed -lni s/a/b/ file.txt", ""],
  ["sed -nlI s/a/b/ file.txt", ""],
  ["perl -Ilib -ne print file.txt", ""],
  ["perl -Ilib -Ilib2 -ne print file.txt", ""],
  ["ruby -Ilib -e puts", ""],
  ["ruby -Ilib:vendor -e puts", ""],
  ["sed -l 5 -n p file.txt", ""],
  ["sed -l5 -n p file.txt", ""],
  ["perl -pes/i/j/ file.txt", ""],
  ["perl -ne print file.txt", ""],
  ["sed -n 1p file.txt", ""],
  ["sed -nE s/x/y/i file.txt", ""],
  ["sed -ffilter.sed file.txt", ""],
  ["perl -MList::Util -ne print file.txt", ""],
  ["ruby -rtime -e puts", ""],
  ["grep -ri needle .", ""],
  ["git diff HEAD > @SANDBOX@/tmp/scratch/review.diff", ""],
  ["git diff HEAD > /tmp/review.diff", ""],
  ["git diff HEAD > @SANDBOX@/repo/notes.md", ""],
  ["git diff HEAD > notes.md", "@SANDBOX@/repo"],
  ["git diff HEAD > notes.md", "@SANDBOX@/tmp/elsewhere"],
  ["git diff HEAD > notes.md", ""],
  ["bash run-tests.sh 2>&1", ""],
  ["echo x >&2 2>&-", ""],
  ["ls 2>/dev/null", ""],
  ["echo x > /dev/stdout 2> /dev/fd/2", ""],
  ["echo x 1> @SANDBOX@/repo/f", ""],
  ["echo x 2> @SANDBOX@/repo/f", ""],
  ["echo x 2>> @SANDBOX@/repo/f", ""],
  ["echo x >| @SANDBOX@/repo/f", ""],
  ["echo x 1>| @SANDBOX@/repo/f", ""],
  ["echo x >& @SANDBOX@/repo/f", ""],
  ["echo x 2>&1 > @SANDBOX@/repo/f", ""],
  ["echo x > \"@SANDBOX@/repo/README.md\"", "@SANDBOX@/tmp/elsewhere"],
  ["echo x > ~/../repo/README.md", "@SANDBOX@/tmp/elsewhere"],
  ["echo x > $HOME/../repo/README.md", "@SANDBOX@/tmp/elsewhere"],
  ["echo x > ~/notes.md", "@SANDBOX@/tmp/elsewhere"],
  ["cd @SANDBOX@/repo && echo x > README.md", "@SANDBOX@/tmp/elsewhere"],
  ["cd @SANDBOX@/repo && rm README.md", "@SANDBOX@/tmp/elsewhere"],
  ["(cd @SANDBOX@/repo && rm README.md)", "@SANDBOX@/tmp/elsewhere"],
  ["cd @SANDBOX@/repo; touch README.md", "@SANDBOX@/tmp/elsewhere"],
  ["builtin cd @SANDBOX@/repo; echo x > README.md", "@SANDBOX@/tmp/elsewhere"],
  ["command cd @SANDBOX@/repo && echo x > README.md", "@SANDBOX@/tmp/elsewhere"],
  ["( cd @SANDBOX@/repo && echo x > f )", "@SANDBOX@/tmp/elsewhere"],
  ["(cd @SANDBOX@/repo; touch README.md; true)", "@SANDBOX@/tmp/elsewhere"],
  ["{ cd @SANDBOX@/repo; }; echo x > README.md", "@SANDBOX@/tmp/elsewhere"],
  ["if true; then cd @SANDBOX@/repo; fi; echo x > README.md", "@SANDBOX@/tmp/elsewhere"],
  ["chdir @SANDBOX@/repo; echo x > README.md", "@SANDBOX@/tmp/elsewhere"],
  ["pushd @SANDBOX@/repo && rm README.md", "@SANDBOX@/tmp/elsewhere"],
  ["pushd @SANDBOX@/repo; echo x > README.md", "@SANDBOX@/tmp/elsewhere"],
  ["popd && rm README.md", "@SANDBOX@/tmp/elsewhere"],
  ["popd; touch README.md", "@SANDBOX@/tmp/elsewhere"],
  ["env -C @SANDBOX@/repo chmod 644 README.md", "@SANDBOX@/tmp/elsewhere"],
  ["env --chdir=@SANDBOX@/repo touch README.md", "@SANDBOX@/tmp/elsewhere"],
  ["echo x >! @SANDBOX@/repo/README.md", "@SANDBOX@/tmp/elsewhere"],
  ["echo x >>! @SANDBOX@/repo/README.md", "@SANDBOX@/tmp/elsewhere"],
  ["echo x > notes.md", "@SANDBOX@/tmp/elsewhere"],
  ["echo x > ~/Developer/scratchpad/notes.md", "@SANDBOX@/tmp/elsewhere"],
  ["rm notes.md", "@SANDBOX@/tmp/elsewhere"],
  ["cd @SANDBOX@/repo && git status --short", "@SANDBOX@/tmp/elsewhere"],
  ["grep -rnE \"git (commit|push)|chmod|rm -rf\" .", "@SANDBOX@/repo"],
  ["rg -n 'git commit; git restore .' skills", "@SANDBOX@/repo"],
  ["grep -rn \"a; rm -rf x\" .", "@SANDBOX@/repo"],
  ["git diff HEAD 2>&1 | head -50", "@SANDBOX@/repo"],
  ["grep -nE '[<>]' f", "@SANDBOX@/repo"],
  ["grep -rn \"\\->\" .", "@SANDBOX@/repo"],
  ["rg -n 'x > y' .", "@SANDBOX@/repo"],
  ["git diff > /dev/null 2>&1", "@SANDBOX@/repo"],
  ["ls 2>/dev/null", "@SANDBOX@/repo"],
  ["git log -1 2>&1 | tail -3", "@SANDBOX@/repo"],
  ["grep -c 'a > b' f 2>/dev/null", "@SANDBOX@/repo"],
  ["printf '%s\\n' 'git stash; chmod 644 x'", "@SANDBOX@/repo"],
  ["grep -n \"x\" f | sed -n \"1,5p\"", "@SANDBOX@/repo"],
  ["awk '$3 > 5' data.txt", "@SANDBOX@/repo"],
  ["awk -F, '{ if ($2 >= 10) print }' data.csv", "@SANDBOX@/repo"],
  ["grep -n \"->\" src/x.php", "@SANDBOX@/repo"],
  ["echo \"$(git status --short 2>&1)\"", "@SANDBOX@/repo"],
  ["echo x > @SANDBOX@/repo/out.txt", "@SANDBOX@/repo"],
  ["echo x > out.txt", "@SANDBOX@/repo"],
  ["grep -rn \"x\" . > notes.txt", "@SANDBOX@/repo"],
  ["cat f 2>&1 > out.txt", "@SANDBOX@/repo"],
  ["echo 'x' > \"@SANDBOX@/repo/q\"", "@SANDBOX@/repo"],
  ["echo \"a\" ; rm -rf @SANDBOX@/repo/x", "@SANDBOX@/repo"],
  ["sh -c 'git status; rm -rf x'", "@SANDBOX@/repo"],
  ["bash -c \"echo a; chmod 644 f\"", "@SANDBOX@/repo"],
  ["perl -e 'print 1; unlink \"x\"'", "@SANDBOX@/repo"],
  ["echo \"$(cd x; rm -rf y)\"", "@SANDBOX@/repo"],
  ["echo $'a\\'b'; rm -rf @SANDBOX@/repo/x", "@SANDBOX@/repo"],
  ["git restore x", "@SANDBOX@/repo"],
  ["grep -n 'a' f; git checkout -- f", "@SANDBOX@/repo"],
  ["\"rm\" -rf @SANDBOX@/repo/x", "@SANDBOX@/repo"],
  ["\\rm -rf @SANDBOX@/repo/x", "@SANDBOX@/repo"],
  ["awk '{ print > \"out.txt\" }' f", "@SANDBOX@/repo"],
  ["cat <<'EOF'\nit's\nEOF\nrm -rf @SANDBOX@/repo/x", "@SANDBOX@/repo"],
  ["\"bash\" -c 'true; rm README.md'", "@SANDBOX@/repo"],
  ["\\bash -c 'true; rm README.md'", "@SANDBOX@/repo"],
  ["$'sh' -c 'true; rm README.md'", "@SANDBOX@/repo"],
  ["gawk '{ print > \"out.txt\" }' f", "@SANDBOX@/repo"],
  ["mawk '{ print > \"out.txt\" }' f", "@SANDBOX@/repo"],
  ["nawk '{ print > \"out.txt\" }' f", "@SANDBOX@/repo"],
  ["# it's a note\nrm README.md", "@SANDBOX@/repo"],
  ["echo x >&2'README.md'", "@SANDBOX@/repo"],
  ["chmod 644 @SANDBOX@/repo/file.txt", ""],
  ["rm -rf @SANDBOX@/repo/src", ""],
  ["echo x > @SANDBOX@/repo/notes.md", ""],
  ["git status", ""],
  ["ls -la", ""],
  ["ls", ""],
  ["chmod 644 file.txt", ""],
  ["rm -rf .", ""],
  ["touch @SANDBOX@/tmp/scratch/x", ""],
  ["sed -i s/a/b/ f", ""],
  ["prettier --write .", ""],
  ["chmod 644 @SANDBOX@/repo/x", "@SANDBOX@/repo"],
  ["git status", "@SANDBOX@/repo"],
  ["echo \"$(git push)\"", "@SANDBOX@/repo"],
  ["x=\"$(git commit -m y)\"", "@SANDBOX@/repo"],
  ["echo \\\"; git push; echo \\\"", "@SANDBOX@/repo"],
  ["$'git' push origin x", "@SANDBOX@/repo"],
  ["$\"git\" push", "@SANDBOX@/repo"],
  ["git${IFS}push", "@SANDBOX@/repo"],
  ["{git,} push", "@SANDBOX@/repo"],
  ["=git push", "@SANDBOX@/repo"],
  ["git -c alias.ci=commit ci -m x", "@SANDBOX@/repo"],
  ["awk 'BEGIN{system(\"git push\")}'", "@SANDBOX@/repo"],
  ["sed '1e git push' f", "@SANDBOX@/repo"],
  ["echo \"$(gh pr merge 5)\"", "@SANDBOX@/repo"],
  ["gh api -X PUT \"repos/o/r/pulls/5/merge?merge_method=squash\"", "@SANDBOX@/repo"],
  ["# it's here\ngit push", "@SANDBOX@/repo"],
  ["echo git push | sh", "@SANDBOX@/repo"],
  ["printf \"git push\" | bash", "@SANDBOX@/repo"],
  ["echo 'git commit -m x' | zsh", "@SANDBOX@/repo"],
  ["echo git push | tclsh", "@SANDBOX@/repo"],
  ["echo git push | xonsh", "@SANDBOX@/repo"],
  ["echo hi # it's\ngit push\n# it's", "@SANDBOX@/repo"],
  ["echo git push > x.sh; bash x.sh", "@SANDBOX@/repo"],
  ["echo git push > x.sh; ./x.sh", "@SANDBOX@/repo"],
  ["echo git push | xargs -I{} sh -c {}", "@SANDBOX@/repo"],
  ["cat <(git push)", "@SANDBOX@/repo"],
  ["echo git push > >(sh)", "@SANDBOX@/repo"],
  ["rg --pre \"git push\" x", "@SANDBOX@/repo"],
  ["git grep -O\"git push\" x", "@SANDBOX@/repo"],
  ["git log; git push", "@SANDBOX@/repo"],
  ["git log --grep x | git push", "@SANDBOX@/repo"],
  ["grep x f || git push", "@SANDBOX@/repo"],
  ["cd x && git push", "@SANDBOX@/repo"],
  ["git push origin --fo\\\nrce", "@SANDBOX@/repo"],
  ["git push $'--force'", "@SANDBOX@/repo"],
  ["git push origin $'+main'", "@SANDBOX@/repo"],
  ["\"git\" push -f", "@SANDBOX@/repo"],
  ["awk '{ print | \"sh\" }' f", "@SANDBOX@/repo"],
  ["awk 'BEGIN { system(\"rm README.md\") }'", "@SANDBOX@/repo"],
  ["expect -c 'spawn sh; send \"rm README.md\"'", "@SANDBOX@/repo"],
  ["echo 'x; rm README.md' | tclsh", "@SANDBOX@/repo"],
  ["lua -e 'x; os.remove(\"README.md\")'", "@SANDBOX@/repo"],
  ["pwsh -c 'x; Remove-Item README.md'", "@SANDBOX@/repo"],
  ["Rscript -e 'x; file.remove(\"README.md\")'", "@SANDBOX@/repo"],
  ["echo hi # it's\nrm README.md\n# it's", "@SANDBOX@/repo"],
  ["echo rm README.md | xonsh", "@SANDBOX@/repo"],
  ["echo \\'; rm README.md; echo \\'", "@SANDBOX@/repo"],
  ["echo \\\"; rm README.md; echo \\\"", "@SANDBOX@/repo"],
  ["echo \\'; git push; echo \\'", "@SANDBOX@/repo"],
  ["echo \"$(rm README.md)\"", "@SANDBOX@/repo"],
  ["cat <<EOF\nit's\nEOF\nrm README.md", "@SANDBOX@/repo"],
  ["sed 's/a/b/w out.txt' f", "@SANDBOX@/repo"],
  ["grep -E 'x' f; git checkout -- f", "@SANDBOX@/repo"],
  ["echo x | tee README.md", "@SANDBOX@/repo"],
  ["git stash", "@SANDBOX@/repo"],
  ["=rm README.md", "@SANDBOX@/repo"],
  ["2>/dev/null rm README.md", "@SANDBOX@/repo"],
  [">README.md echo x", "@SANDBOX@/repo"],
  ["FOO=1 rm README.md", "@SANDBOX@/repo"],
  ["A=1 B=2 chmod 644 README.md", "@SANDBOX@/repo"],
  ["doas rm README.md", "@SANDBOX@/repo"],
  ["find . -exec rm {} \\;", "@SANDBOX@/repo"],
  ["find . -name x -execdir rm README.md \\;", "@SANDBOX@/repo"],
  ["{rm,README.md}", "@SANDBOX@/repo"],
  ["rm {README,x}.md", "@SANDBOX@/repo"],
  ["grep -rn 'x' . > README.md", "@SANDBOX@/repo"],
  ["echo git push > x.sh; csh x.sh", "@SANDBOX@/repo"],
  ["echo git push > x.sh; tcsh x.sh", "@SANDBOX@/repo"],
  ["echo git push > x.sh; make -f x.sh", "@SANDBOX@/repo"],
  ["git grep \"--open-files-in-pager=git push\" foo", "@SANDBOX@/repo"],
  ["git grep \"-Ogit push\" foo", "@SANDBOX@/repo"],
  ["rg \"--pre=git push\" foo", "@SANDBOX@/repo"],
  ["git grep --open-files=git push foo", "@SANDBOX@/repo"],
  ["git grep -nOgit push foo", "@SANDBOX@/repo"],
  ["git -c alias.x='!rm README.md' x", "@SANDBOX@/repo"],
  ["git -c core.pager='sh -c \"rm README.md\"' log", "@SANDBOX@/repo"],
  ["git -c core.fsmonitor='rm README.md' status", "@SANDBOX@/repo"],
  ["git -c diff.external='rm README.md' diff", "@SANDBOX@/repo"],
  ["git -c gpg.program='rm README.md' log --show-signature", "@SANDBOX@/repo"],
  ["git -c 'alias.x=!rm README.md; true' x", "@SANDBOX@/repo"],
  ["git grep -O\"rm README.md\" x", "@SANDBOX@/repo"],
  ["git grep -O git push x", "@SANDBOX@/repo"],
  ["rg --pre git push foo", "@SANDBOX@/repo"],
  ["git grep --open-files git push foo", "@SANDBOX@/repo"],
  ["rg \"git push\" *", "@SANDBOX@/repo"],
  ["git log --grep=push *", "@SANDBOX@/repo"],
  ["grep -rn \"git push\" ?", "@SANDBOX@/repo"],
  ["git log --format=%GG --grep=push", "@SANDBOX@/repo"],
  ["git log --pretty=format:%G? --grep push", "@SANDBOX@/repo"],
  ["git show --format=%GS push", "@SANDBOX@/repo"],
  ["rg \"git push\" ^x", "@SANDBOX@/repo"],
  ["git log --grep=push ^x", "@SANDBOX@/repo"],
  ["grep -rn \"git push\" x#", "@SANDBOX@/repo"],
  ["rg \"git push\" a~b", "@SANDBOX@/repo"],
  ["echo git push > x.sh", "@SANDBOX@/repo"],
  ["git log --grep push > out.txt", "@SANDBOX@/repo"],
  ["echo git push >> ~/.bashrc", "@SANDBOX@/repo"],
]

// The sandbox the review cases ran in: d a directory, f a file, l a link
// and its target.
export const REVIEW_TREE: readonly (readonly string[])[] = [
  ["d", "home"],
  ["d", "home/Developer"],
  ["d", "home/Developer/scratchpad"],
  ["d", "linked-home"],
  ["d", "linked-home/Developer"],
  ["l", "linked-home/Developer/scratchpad", "@SANDBOX@/repo"],
  ["d", "repo"],
  ["l", "repo/dir-link-out", "@SANDBOX@/tmp/scratch"],
  ["l", "repo/link-out", "@SANDBOX@/tmp/scratch/target.txt"],
  ["d", "repo/src"],
  ["d", "session-pad"],
  ["d", "tmp"],
  ["d", "tmp/elsewhere"],
  ["l", "tmp/link-into-tree", "@SANDBOX@/repo/src"],
  ["d", "tmp/scratch"],
  ["f", "tmp/scratch/target.txt"],
]
